webapp/webapp/blueprints/wordpair/views.py
from flask import Blueprint, render_template, request, flash, session, render_template_string, Response
from jinja2_fragments.flask import render_block
from webapp.blueprints.wordpair.models import User, Keyword
from celery.result import AsyncResult
from pprint import pprint

wordpair = Blueprint('wordpair', __name__, template_folder='templates', url_prefix="/pair/<int:id>")
def oobify(html, swap_value='true'):
    return html.replace('>', f' hx-swap-oob="{swap_value}">', 1)

@wordpair.route("/")
def wordpairpage(id):
    from webapp.app import wordlist
    user = User.get_user(session['user_id'])
    wp = wordlist.get(id)
    kw = user.get_keyword(wp)
    if kw is None:
        return render_template("wordpair.jinja", wordlist=wordlist, 
                               wordpair=wp, currentid=id)
    keyword = kw.keyword
    visual_cue = kw.visual_cue
    verbal_cue = kw.verbal_cue
    generated_by = kw.generated_by
    return render_template("wordpair.jinja", wordlist=wordlist, 
                           wordpair=wp, keyword=keyword, 
                           verbal_cue=verbal_cue,
                           visual_cue=visual_cue,
                           generated_by=generated_by,
                           currentid=id) 
    

@wordpair.route("/keyword", methods=["GET", "POST"])
def keyword(id):
    from webapp.app import wordlist
    wp = wordlist.get(id)
    if request.method == "POST":
        from webapp.blueprints.wordpair.tasks import generate_keywords
        print("A")
        result = generate_keywords.delay(user=None, foreign_lang=wordlist.foreign_lang, wordpair=wp)
        return render_template("loadingwords.jinja", get_url='keyword', result=result)
    if request.method == "GET":
        taskid = request.args.get("taskid")
        result = AsyncResult(taskid)
        if result.ready():
            print("B") 
            return render_template("threewords.jinja", get_url='keyword', 
                                   result=result, limit = 1, wordpair=wp)
        else:
            print("C")
            return render_template("loadingwords.jinja", get_url='keyword', result=result)

@wordpair.route("/verbalcue", methods=["GET", "POST"])
def generateverbalcue(id):
    from webapp.blueprints.wordpair.tasks import generate_verbalcue
    from webapp.app import wordlist
    wp = wordlist.get(id)
    kw = User.get_user(session['user_id']).get_keyword(wp)
    if request.method == "POST":
        result = generate_verbalcue.delay(kw=kw)
        return render_template("loadingwords.jinja", get_url="verbalcue", result=result)
    if request.method == "GET":
        u = User.get_user(session['user_id'])
        taskid = request.args.get("taskid")
        result = AsyncResult(taskid)
        if result.ready():
            u.add_verbal_cue(wp, result.result)
            return render_block("wordpair.jinja", "verbalcueblock", verbal_cue=result.result) \
            + render_block("wordpair.jinja", "visualcueblock", verbal_cue=True)
        else:
            return render_template("loadingwords.jinja", get_url="verbalcue", result=result)

@wordpair.route("/visualcue", methods=["GET", "POST"])
def generatevisualcue(id):
    from webapp.blueprints.wordpair.tasks import generate_visualcue
    if request.method == "POST":
        kw = User.get_user((session['user_id'])).get_keyword(id)
        result = generate_visualcue.delay(kw = kw)
        return render_template("loadingwords.jinja", get_url="visualcue", result=result)
    if request.method == "GET":
        from webapp.app import wordlist
        wp = wordlist.get(id)
        u = User.get_user(session['user_id'])
        # vsc = u.get_visual_cue(wp)
        # if vsc:
        #     return render_block("wordpair.jinja", "visualcueblock", visual_cue=result.result)
        taskid = request.args.get("taskid")
        result = AsyncResult(taskid)
        if result.ready():
            u.add_visual_cue(wp, result.result)
            return render_block("wordpair.jinja", "visualcueblock", visual_cue=result.result) \
            + oobify(render_block("wordpair.jinja", "footerblock", visual_cue=True, verbal_cue=True))
        else:
            return render_template("loadingwords.jinja", get_url="visualcue", result=result)

@wordpair.route("/disagree", methods=["POST"])
def generate(id):
    from webapp.app import wordlist
    taskid = request.form.get("taskid")
    result = AsyncResult(taskid)
    return render_template("threewords.jinja", result=result,
                           wordpair=wordlist.get(id))

@wordpair.post("/regen")
def regen(id):
    type = request.form.get("type")
    if type == "visualcue":
        return render_block("wordpair.jinja", "visualcueblock", verbal_cue=True)
    if type == "verbalcue":
        return render_block("wordpair.jinja", "verbalcueblock", keyword=True) \
        + "<div id='visualcue' hx-swap-oob='true'></div>"


@wordpair.route("/testoob", methods=["GET", "POST"])
def testoob(id):
    if request.method == "POST":
        text = '''
        <div>I have been swapped</div> 
        <div id="lol1">Lol1 has been swapped too!</div>
        '''
        resp = Response(text)
        resp.headers['HX-Swap-Oob'] = "#lol1"
        return resp
    if request.method == "GET":
        return render_template("testdeleteme.jinja")

@wordpair.post("/submitpreference")
def submitpreference(id):
    from webapp.app import wordlist
    if request.form.get('selectedOption') == 'customOption':
        preference = request.form['text'].strip().lower()
        generated_by = "user"
    else:
        preference = request.form.get('selectedOption').split(".")[1]
        generated_by = "myLLM" + request.form.get('selectedOption').split(".")[0]

    print("Preference:", preference)
    print(preference in (None, ''))
    taskid = request.form.get("taskid")
    result = AsyncResult(taskid)
    if preference in (None, ''): 
        flash("Cannot be empty")
        return render_template("threewords.jinja", result=result, 
                               isempty=True, wordpair=wordlist.get(id))
    print("pref:", preference)
    print("generated by:", generated_by)
    # Save keyword to mongo db
    from webapp.app import wordlist
    wp = wordlist.get(id)
    kw = Keyword(wordpair=wp, keyword=preference, generated_by=generated_by)
    User.get_user(session['user_id']).add_keyword(kw)

    return render_block("wordpair.jinja", "keywordblock", keyword=preference, wordpair=wp) \
        + render_block("wordpair.jinja", "verbalcueblock", keyword=True)

@wordpair.route("/keywords")
def topwords(id):
    return "list of top keywords"


webapp/webapp/templates/base.jinja
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon"
              href="{{ url_for('static', filename='favicon.ico') }}">
        <!--------- CSS --------->
        <!-- <link rel="stylesheet"
       href="{{ url_for('static', filename='styles/marx.min.css') }}"> -->
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.pumpkin.min.css">
        {# href="{{ url_for('static', filename='styles/pico.pumpkin.min.css') }}"> #}
        <link rel="stylesheet"
              href="{{ url_for('static', filename='styles/main.css') }}">
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.colors.min.css" />
        <!-- <link rel="stylesheet"
       href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css"> -->
        <!-- <link rel="stylesheet"
       href="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.15.0/cdn/themes/light.css" /> -->
        <!--------- JS ---------->
        <script src="{{ url_for('static', filename='scripts/htmx.min.js')}}"></script>
        {# <script src="{{ url_for('static', filename='scripts/response-oob.js')}}"></script> #}
        <!-- <script src="https://unpkg.com/hyperscript.org@0.9.12"></script> -->
        {# <script src="https:///unpkg.com/alpinejs" defer></script> #}
        <script src="{{ url_for('static', filename='scripts/alpinejs.min.js') }}"
                defer></script>
        <!-- <script type="module" src="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.15.0/cdn/shoelace-autoloader.js"></script> -->
        <title>
            {% block title %}
                WebApp
            {% endblock title %}
        </title>
    </head>
    <body hx-boost="true">
        <header class="container-fluid">
            <nav>
                <ul>
                    <li>
                        <a href="{{ url_for("index") }}">
                            <h3>KWM experiment</h3>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="{{ url_for("index") }}">Home</a>
                    </li>
                    <li>
                        <a href="{{ url_for("logout") }}">Logout</a>
                    </li>
                </ul>
            </nav>
        </header>
        <main class="container">
            {% block content %}
                Content here
            {% endblock content %}
        </main>
    </body>
</html>

webapp/webapp/templates/break.jinja
{% extends "base.jinja" %}
{% block content %}
    <h1>Take a break</h1>
    <ol>
        <li>
            Click <b><a href="https://duckduckgo.com/?va=g&t=hh&q=5+minute+timer&ia=answer"
                        target="_blank">this link</a></b> to set a timer for 5 minutes.
        </li>
        <li>click <a href="https://slowroads.io" target="_blank">this link</a> to take a break.</li>
        <li>When the timer is done, continue.</li>
    </ol>
    <a class="secondary" href='{{ url_for("finaltest") }}'>Continue ></a>
{% endblock content %}

webapp/webapp/templates/finaltest.jinja
{% extends "base.jinja" %}
{% block title %}
    Final test
{% endblock title %}
Final test
{% block content %}
    <h1>Final test</h1>
    <p>
        You will now be tested on all words you've learnt. You must answer every question. If you don't know a word, write <i>"idk", "n/a"</i> or <i>"-"</i>.
    </p>
    <p>After submitting, you can't go back.</p>
    <form action="">
        {% for k, wordpair in wordlist.words.items() %}
            <br>
            <article>
                <header class="secondary centered">
                    {{ k }}
                </header>
                <div class="grid text-center">
                    <div id="foreignword">
                        <small>{{ wordlist.foreign_lang }}</small>
                        <h1>{{ wordpair.foreign_word }}</h1>
                    </div>
                    <div id="nativeword">
                        <small>{{ wordlist.native_lang }}</small>
                        <input name="answer{{ loop.index }}" required>
                    </div>
                </div>
            </article>
            <br>
            <hr>
        {% endfor %}
        <p>Once submitted, your answers cannot be changed. Please review carefully.</p>
    <button type="submit" formmethod="post">Submit test</button>
</form>
{% endblock content %}

webapp/webapp/templates/login.jinja
{% extends "base.jinja" %}

{% block content %}
<form>
    {% if error %}
    <input type="text" name="id" placeholder="User id invalid" aria-label="User id" aria-invalid="true" required />
    {% else %}
    <input type="text" name="id" placeholder="User id" aria-label="User id" required />
    {% endif %}
    <input type="submit" value="Log in"/>
</form>
{% endblock content %}

webapp/webapp/templates/review.jinja
{% extends "base.jinja" %}
{% block title %}
    Review
{% endblock title %}
{% block content %}
    <form action="{{ url_for("review") }}" method="post">
        <h1>Review</h1>
        <p>That was it for the test. You're almost done! I would really appreciate your feedback on this experiment</p>
        <h2>Helpfulness</h2>
        <p>How helpful did you find the keywords? Please rate them from 1 (not helpful at all) to 5 (extremely helpful).</p>
        {% for i, wp in wordlist.words.items() %}
            <div class="grid">
                <p>{{ wp.foreign_word }}</p>
                <i>{{ user.get_keyword(wp).keyword }}</i>
                <p>{{ wp.native_word|capitalize }}</p>
                <select name="helpfulness{{ loop.index }}" required>
                    <option selected disabled value="">Helpfulness</option>
                    <option>1 - Not helpful at all</option>
                    <option>2 - Slightly helpful</option>
                    <option>3 - Somewhat helpful</option>
                    <option>4 - Very helpful</option>
                    <option>5 - Extremely helpful</option>
                </select>
            </div>
        {% endfor %}
        <h2>Open feedback</h2>
        <p>
            Did you notice any difference between when you could choose your keyword, and the ones where you couldn't? If so, what difference?
        </p>
        <textarea name="differences"></textarea>
        <p>Do you have any other thoughts, feedback or ideas? Anything goes.</p>
        <textarea name="feedback"></textarea>
        <input type="submit" value="Submit">
    </form>
{% endblock content %}

webapp/webapp/templates/testpage.jinja
{% extends "base.jinja" %}
{% block title %}
    Test
{% endblock title %}
{% block content %}
    <h1>Test on words {{ start }} - {{ end-1 }}</h1>
    <p>
        Write the English translation of the following words.
        Use the keyword method to remember the words.
        This is just for reinforcing your memory. You will not get feedback.
        If you don't know a word, write "idk" or "-".
    </p>
    <hr />
    <form method="post">
        {% for i in range(start, end) %}
            <label for="translation{{ i }}">{{ wordlist.words.get(i).foreign_word }}</label>
            <input type="text" name="answer{{ i }}" required />
        {% endfor %}
        {% set redirect_url = url_for("index") %}
        {% if start == 1 %}
            {% set redirect_url = url_for('wordpair.wordpairpage', id=end) %}
        {% elif start == 13 %}
            {% set redirect_url = url_for('wordpair.wordpairpage', id=end) %}
        {% elif start == 25 %}
            {% set redirect_url = url_for('break_page') %}
        {% endif %}
        <input type="hidden" name="redirect_url" value="{{ redirect_url }}">
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

webapp/webapp/templates/thankyou.jinja
{% extends "base.jinja" %}
{% block title %}
:)
{% endblock title %}

{% block content %}
<article class="centered">
<p>Thanks for your participation.</p>
<p>It is very much appreciated</p>
<p><3</p>
</article>
{% endblock content %}

webapp/webapp/templates/wordlist.jinja
{% extends "base.jinja" %}
{% block title %}
    Wordlist
{% endblock title %}
{% block content %}
    {# <mark> <b>Debug only:</b> You can reset the keywords by visiting <a href="/resetkeywords">/resetkeywords</a></mark>
    <hr> #}
    <hgroup>
        <h1>Instructions</h1>
        <p>Read this before starting. You can always return here later.</p>
    </hgroup>
    <h3>The Keyword Method</h3>
    <p>
        In this experiment, you will be using the <i>keyword method</i> to learn words in a foreign language. 
        The keyword method is a technique used for learning new words by associating them with a <i>keyword</i> in your native language.
    </p>
    <p>
        As an example, consider the following pair of words:
        <ul>
            <li>
                French: <i>poisson</i>
            </li>
            <li>
                English: <i>fish</i>
            </li>
        </ul>
    </p>
    <p>
        The French word <i>poisson</i> looks a lot like the English word <i>poison</i>.
        You can link the two words together with a vivid mental image, for example, by imagining a fish drinking a bottle of poison.
    </p>
    <p>
        Next time you see the word <i>poisson</i>, you will remember the keyword <i>poison</i>, which reminds you of the image, and thus the translation <i>fish</i>.
    </p>
    <h3>This Experiment</h3>
    <p>
        You will be presented with 36 German words and their translations, one at a time.
        For each pair of words, a keyword is generated. 
        For some of the pairs, if you don't think the association between the German word and the keyword is strong enough, you can choose from other options, or input your own.
        For the others, you should use the given keyword.
    </p>
    <p>
        After the keyword has been set, the interface will look like this.
        You can see the keyword (A), a description and picture (B), and the option to get a new description or picture (C).
    </p>
    <div class="centered">
        <img width="900" alt="interface"
             src="{{ url_for('static', filename='images/interface.jpg') }}" />
    </div>
    <p>
        It is important for you to close your eyes for a few seconds, and try to strongly imagine a visual scene connecting the given keyword with the English meaning.
        The description and pictures are there to help you, but <u>you may ignore them</u> and create your own mental image.
    </p>
    <p>After every set of 12 words, you will have a small test, to reinforce the previously learnt words.</p>
    <p>At the end, you'll have a short break and then a final test.</p>
    <p>If you have any questions, please ask Safouane.</p>
    <p>
        When you're ready, <a href="{{ url_for('wordpair.wordpairpage', id=1) }}">click here to start</a>.
    </p>
    {# <ol>
        {% for pair in wordlist.words.values() %}
            <li>
                <article>
                    <a href="{{ url_for('wordpair.wordpairpage', id=loop.index) }}">{{ pair.native_word }} - {{ pair.foreign_word }}</a>
                </article>
            </li>
        {% endfor %}
    </ol> #}
{% endblock content %}